# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Aug 13 21:01:47 2014
#      by: PyQt5 UI code generator 5.3.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(637, 543)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 611, 481))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.gdlyMain = QtWidgets.QGridLayout(self.horizontalLayoutWidget_4)
        self.gdlyMain.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gdlyMain.setContentsMargins(5, 5, 5, 5)
        self.gdlyMain.setObjectName("gdlyMain")
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget_4)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(220, 10, 381, 401))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.hzlyTbwResult = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.hzlyTbwResult.setContentsMargins(5, 5, 5, 5)
        self.hzlyTbwResult.setObjectName("hzlyTbwResult")
        self.tbwResult = QtWidgets.QTableWidget(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbwResult.sizePolicy().hasHeightForWidth())
        self.tbwResult.setSizePolicy(sizePolicy)
        self.tbwResult.setAutoFillBackground(True)
        self.tbwResult.setLineWidth(2)
        self.tbwResult.setMidLineWidth(1)
        self.tbwResult.setWordWrap(False)
        self.tbwResult.setRowCount(4)
        self.tbwResult.setColumnCount(4)
        self.tbwResult.setObjectName("tbwResult")
        self.hzlyTbwResult.addWidget(self.tbwResult)
        self.hzlyTbwResult.setStretch(0, 1)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 201, 401))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabTasks = QtWidgets.QTabWidget(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabTasks.sizePolicy().hasHeightForWidth())
        self.tabTasks.setSizePolicy(sizePolicy)
        self.tabTasks.setObjectName("tabTasks")
        self.tabTaskRuning = QtWidgets.QWidget()
        self.tabTaskRuning.setAutoFillBackground(False)
        self.tabTaskRuning.setObjectName("tabTaskRuning")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tabTaskRuning)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 181, 361))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.hzlyRunningTask = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.hzlyRunningTask.setContentsMargins(5, 5, 5, 5)
        self.hzlyRunningTask.setObjectName("hzlyRunningTask")
        self.listRunningTasks = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.listRunningTasks.setObjectName("listRunningTasks")
        self.hzlyRunningTask.addWidget(self.listRunningTasks)
        self.tabTasks.addTab(self.tabTaskRuning, "")
        self.tabTaskCompleted = QtWidgets.QWidget()
        self.tabTaskCompleted.setObjectName("tabTaskCompleted")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tabTaskCompleted)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 191, 371))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.hzlyCompletedTask = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.hzlyCompletedTask.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.hzlyCompletedTask.setContentsMargins(5, 5, 5, 5)
        self.hzlyCompletedTask.setObjectName("hzlyCompletedTask")
        self.listCompletedTasks = QtWidgets.QListView(self.horizontalLayoutWidget_2)
        self.listCompletedTasks.setObjectName("listCompletedTasks")
        self.hzlyCompletedTask.addWidget(self.listCompletedTasks)
        self.tabTasks.addTab(self.tabTaskCompleted, "")
        self.horizontalLayout.addWidget(self.tabTasks)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 422, 591, 83))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vtlyOutput = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vtlyOutput.setSpacing(6)
        self.vtlyOutput.setContentsMargins(5, 5, 5, 5)
        self.vtlyOutput.setObjectName("vtlyOutput")
        self.listOutput = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listOutput.setObjectName("listOutput")
        self.vtlyOutput.addWidget(self.listOutput)
        self.gdlyMain.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gdlyMain.setRowStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 637, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuExport = QtWidgets.QMenu(self.menuFile)
        self.menuExport.setObjectName("menuExport")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuUser = QtWidgets.QMenu(self.menubar)
        self.menuUser.setObjectName("menuUser")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionTo_Excel = QtWidgets.QAction(MainWindow)
        self.actionTo_Excel.setObjectName("actionTo_Excel")
        self.actionNew_Task = QtWidgets.QAction(MainWindow)
        self.actionNew_Task.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionNew_Task.setObjectName("actionNew_Task")
        self.actionRegiste = QtWidgets.QAction(MainWindow)
        self.actionRegiste.setObjectName("actionRegiste")
        self.actionLogout = QtWidgets.QAction(MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionTo_File = QtWidgets.QAction(MainWindow)
        self.actionTo_File.setObjectName("actionTo_File")
        self.menuExport.addAction(self.actionTo_Excel)
        self.menuExport.addAction(self.actionTo_File)
        self.menuFile.addAction(self.actionNew_Task)
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuUser.addAction(self.actionRegiste)
        self.menuUser.addAction(self.actionLogin)
        self.menuUser.addAction(self.actionLogout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuUser.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.retranslateUi(MainWindow)
        self.tabTasks.setCurrentIndex(0)
        MainWindow.destroyed.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QT"))
        self.tabTaskRuning.setStatusTip(_translate("MainWindow", "Task is running"))
        self.tabTasks.setTabText(self.tabTasks.indexOf(self.tabTaskRuning), _translate("MainWindow", "Tab 1"))
        self.tabTasks.setTabText(self.tabTasks.indexOf(self.tabTaskCompleted), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "文件"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuHelp.setTitle(_translate("MainWindow", "帮助"))
        self.menuUser.setTitle(_translate("MainWindow", "用户"))
        self.menuView.setTitle(_translate("MainWindow", "视图"))
        self.menuEdit.setTitle(_translate("MainWindow", "编辑"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))
        self.actionTo_Excel.setText(_translate("MainWindow", "To Excel"))
        self.actionNew_Task.setText(_translate("MainWindow", "New Task"))
        self.actionNew_Task.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionRegiste.setText(_translate("MainWindow", "Registe"))
        self.actionRegiste.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionLogout.setText(_translate("MainWindow", "Logout"))
        self.actionTo_File.setText(_translate("MainWindow", "To File"))

